# Generated by Django 4.0.6 on 2022-07-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("middle_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("birthday", models.DateField()),
            ],
        ),
    ]
