# Generated by Django 4.0.6 on 2022-07-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="middle_name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
