# Generated by Django 4.0.6 on 2022-07-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_clientjob_client_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("price", models.IntegerField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="services",
            field=models.ManyToManyField(
                related_name="clients", to="clients.clientservices"
            ),
        ),
    ]
