# Generated by Django 4.0.6 on 2022-07-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_clientservices_client_services"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientServices",
            new_name="ClientService",
        ),
    ]
