# Generated by Django 4.0.6 on 2022-07-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_rename_clientservices_clientservice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientdetail",
            old_name="salary",
            new_name="income",
        ),
    ]
